## Import thư viện

In [2]:
import numpy as np

## Phần 1: Tạo mảng
### Tạo mảng 1 chiều

In [ ]:
# 1. Tạo một mảng numpy 1 chiều even_numbers chứa 10 phần tử là các số chẵn trong phạm vi [2,20] 
even_number = np.random.randint(2,21, size=10)
even_number

array([[0.43128302, 0.73082266, 0.61631828, 0.11317425, 0.98432907,
        0.146138  , 0.28416016, 0.6299384 , 0.64815272, 0.19426443,
        0.44912672, 0.44822685, 0.60774769, 0.99219555, 0.60097675,
        0.46224795, 0.73053643, 0.20694759, 0.4505656 , 0.10151089,
        0.09637774],
       [0.81834508, 0.46264604, 0.77720299, 0.07274141, 0.31363424,
        0.72816186, 0.98253839, 0.33969598, 0.5046889 , 0.6344618 ,
        0.49128947, 0.6498774 , 0.18999971, 0.85531806, 0.58695067,
        0.21977867, 0.72208215, 0.22100882, 0.06833507, 0.33608755,
        0.21346183]])

In [8]:
# 2. Tạo một mảng numpy 1 chiều chứa 5 phần tử là các số chia cho 5 dư 1 (số nguyên có dạng 5x + 1) trong phạm vi [1,21].
mang = np.array([5 * i + 1 for i in range(5)])
mang

array([ 1,  6, 11, 16, 21])

In [5]:
# 3.Tạo 1 mảng 1 chiều gồm 11 phần tử cách đều nhau từ 0 đến 1
array_ = np.linspace(0,1,11) 
array_
# Cho biết khoảng cách giữa các giá trị retstep: 
retstep = array_[1] - array_[2]
retstep

np.float64(-0.1)

In [9]:
# 4.Tạo 1 mảng 1 chiều gồm 5 phần tử là các số nguyên ngẫu nhiên từ 1 đến 20
array_ = np.random.randint(1,20,5)
array_

array([ 4, 15, 16,  7, 17], dtype=int32)

In [11]:
# 5.Tạo mảng numpy 1 chiều chứa 10 phần tử với các phần tử ở index chẵn là 0 và ở index lẻ là số lẻ
array_  = np.array([0 if i % 2 == 0 else i for i in range(1,10) ])
array_ 

array([1, 0, 3, 0, 5, 0, 7, 0, 9])

In [ ]:
# 6.Tạo 1 mảng 1 chiều gồm 10 phần tử có các phần tử ở index [0,3,6,9] là 3 và các phần tử còn lại là 1 


In [ ]:
# 7. Tạo 1 mảng 1 chiều gồm 5 phần tử là các giá trị ngẫu nhiên (không trùng nhau) chia hết cho 3 và nhỏ hơn 30
np.random.seed(5)
# Tạo mảng gồm các phần tử nhỏ hơn 30 và chia hết cho 3

# Tạo mảng gồm 5 phần tử ngẫu nhiên (không trùng nhau) từ mảng vừa tạo

### Tạo mảng 2 chiều

In [ ]:
# 8.Tạo mảng 2 chiều (3x4) arr_2d với các số chẵn ngẫu nhiên (không trùng nhau) < 50
np.random.seed(1)


In [ ]:
# 9. Tạo một mảng numpy 2 chiều (6x6) với các giá trị biên là 1 và các giá trị còn lại là 0
# Tạo một mảng 2 chiều (6x6) với tất cả giá trị là 1


In [ ]:
# 10. Tạo một mảng numpy 2 chiều (3x3) với các giá trị trên đường chéo chính là 1 và các giá trị còn lại là 0 

# mảng kết quả


## Phần 2: Truy xuất
### Mảng 1 chiều
Từ mảng even_numbers đã tạo ở câu 1. Hãy thực hiện các truy xuất sau:

In [ ]:
# 11. Truy xuất giá trị phần tử thứ 3 của mảng even_numbers


In [ ]:
# 12. Truy xuất các phần tử từ vị trí thứ 2 đến vị trí thứ 4 (bao gồm cả vị trí thứ 4) của mảng even_numbers


In [ ]:
# 13.Truy xuất các phần tử lớn hơn 10 từ mảng even_numbers


In [ ]:
# 14. Truy xuất các phần tử chia hết cho 3 từ mảng even_numbers và lớn hơn 10


### Mảng 2 chiều
Từ mảng arr_2d đã tạo ở câu 8. Hãy thực hiện các truy xuất sau:

In [ ]:
# 15.Cho biết phần tử ở hàng thứ 2 và cột thứ 3 của mảng arr_2d


In [ ]:
# 16. Hiển thị toàn bộ hàng 1 của mảng arr_2d


In [ ]:
# 17. Hiển thị toàn bộ cột 2 của mảng arr_2d


In [ ]:
# 18. Lọc các phần tử trong mảng arr_2d lớn hơn 30


In [ ]:
# 19. Lọc ra các dòng có phần tử ở cột thứ 2 trong mảng arr_2d chia hết cho 4


In [ ]:
# 20. Cho biết các giá trị trong mảng arr_2d nằm trong khoảng từ [10, 30]


## Phần 3: Thêm, xóa, sửa phần tử trong mảng
### Mảng 1 chiều
Từ mảng even_numbers đã tạo ở câu 1. Hãy thực hiện các yêu cầu sau:

In [ ]:
# 21. Thêm giá trị 22 vào cuối mảng 


In [ ]:
# 22. Thêm giá trị 30 vào vị trí thứ 5 của mảng


In [ ]:
# 23. Tạo mảng temp là mảng even_numbers đã xóa giá trị tại vị trí thứ 7 


In [ ]:
# 24. Tạo mảng temp là mảng even_numbers đã xóa giá trị 8


In [ ]:
# 25. Thay đổi các giá trị < 10 từ mảng even_numbers thành 10


### Mảng 2 chiều
Từ mảng arr_2d đã tạo ở câu 8. Hãy thực hiện các yêu cầu sau:

In [ ]:
# 26. Thêm hàng mới [10, 16, 20, 24] vào cuối mảng arr_2d


In [ ]:
# 27. Thêm cột mới [50, 60, 70, 80] vào cuối mảng arr_2d


In [ ]:
# 28. Tạo mảng temp là mảng arr_2d đã xóa hàng thứ 2


In [ ]:
# 29. Tạo mảng temp là mảng arr_2d đã xóa cột thứ 3


In [ ]:
# 30. Sửa giá trị tại dòng 1, cột 2 thành 30


In [ ]:
# 31. Sửa các giá trị lớn hơn 10 và nhỏ hơn 20 trong arr_2d thành 20


In [ ]:
# 32. Sửa các giá trị nhỏ hơn 30 và không chia hết cho 4 tại dòng đầu tiên trong arr_2d thành 30
