In [3]:
import numpy as np  


In [8]:

np.random.seed(42)  
array = np.random.randint(50, 500, size=(8, 8))  

print(array)  



[[152 485 398 320 156 121 238  70]
 [152 171 264 380 137 422 149 409]
 [201 180 199 358 307 393 463 343]
 [435 241 493 326 210 363  71 302]
 [285 394  98 108 219 237 320 239]
 [495 224 495 100 413 104 293 369]
 [180 356 184  70 378 216 323 437]
 [138 365  63 291 314 395 102 435]]


In [7]:
max_idx = np.unravel_index(np.argmax(array), array.shape)  
min_idx = np.unravel_index(np.argmin(array), array.shape)  

print("\nChỉ số của phần tử lớn nhất trong mảng: ", max_idx)  
print("Chỉ số của phần tử nhỏ nhất trong mảng: ", min_idx)  


Chỉ số của phần tử lớn nhất trong mảng:  (np.int64(5), np.int64(0))
Chỉ số của phần tử nhỏ nhất trong mảng:  (np.int64(7), np.int64(2))


In [ ]:
def is_prime(num):  
    if num < 2:  
        return False  
    for i in range(2, int(num**0.5) + 1):  
        if num % i == 0:  
            return False  
    return True  



Tổng của tất cả các phần tử có giá trị là số nguyên tố trong mảng:  2508


In [ ]:

prime_filter = np.vectorize(is_prime)  
prime_elements = array[prime_filter(array)]  


In [ ]:

prime_sum = np.sum(prime_elements)  
print("\nTổng của tất cả các phần tử có giá trị là số nguyên tố trong mảng: ", prime_sum)  