In [2]:
import numpy as np 

In [ ]:
# Yêu cầu: Tạo một mảng NumPy từ danh sách sau: [10, 20, 30, 40, 50]
arr01 = np.array([10,20, 30 ,40, 50, 60])
arr01 

SyntaxError: invalid syntax (3099581883.py, line 3)

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>
  Bài Tập 1: Sử Dụng np.array()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo một mảng NumPy kích thước 3x4 chứa toàn số 0.
arr02 = np.zeros([3, 4])
arr02

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>
  Bài Tập 2: Sử Dụng np.zeros()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo một mảng NumPy kích thước 2x5 chứa toàn số 1.
arr03 = np.ones([2,5])
arr03

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 3: Sử Dụng np.ones()
</pre>
  
</details>

In [6]:
# Yêu cầu: Tạo một mảng NumPy chứa các số từ 5 đến 15 (không bao gồm 15), với bước nhảy là 2.
arr04 = np.arange(5,15,2,int)
arr04

array([ 5,  7,  9, 11, 13])

<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 4: Sử Dụng np.arange()
</pre>
  
</details>

In [8]:
# Yêu cầu: Tạo một mảng NumPy chứa 10 số có giá trị từ 0 đến 1, được chia đều.
arr05 = np.linspace(0, 1, 10)
arr05

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 5: Sử Dụng np.linspace()
</pre>
  
</details>

In [12]:
# Yêu cầu: Tạo một mảng NumPy 2x3 chứa các giá trị ngẫu nhiên trong khoảng [0, 1).
arr6 = np.random.rand(2,3)
arr6

array([[0.70792371, 0.77201277, 0.78258541],
       [0.82012559, 0.88725348, 0.347992  ]])

<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 1: Sử Dụng np.random.rand()
</pre>
  
</details>

In [16]:
# Tạo một mảng NumPy chứa các số từ 0 đến 8. Sau đó, chia mảng này thành 3 mảng con bằng nhau.
arr_first = np.arange(0,9)
arr7 = np.split(arr_first, 3)
arr7

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 2: Sử Dụng np.split()
</pre>
  
</details>

In [32]:
# Yêu cầu: Tạo một mảng NumPy một chiều chứa 9 phần tử. Sau đó, chuyển đổi mảng này thành mảng hai chiều 3x3.
arr8 = np.linspace(0,9, num = 9)
arr8 = np.reshape(arr8, (3,3))
arr8 = np.reshape(arr8, (1,9))
arr8

array([[0.   , 1.125, 2.25 , 3.375, 4.5  , 5.625, 6.75 , 7.875, 9.   ]])

<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 3: Sử Dụng np.reshape()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo hai mảng NumPy, một mảng chứa các số lẻ từ 1 đến 5 và một mảng chứa các số chẵn từ 2 đến 6. Nối hai mảng này theo chiều ngang.


<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 4: Sử Dụng np.concatenate()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo một mảng NumPy 2x3. Sau đó, thực hiện chuyển vị mảng này.


<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 5: Sử Dụng np.transpose()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo hai mảng NumPy, mỗi mảng có kích thước 1x3. Xếp chồng hai mảng này theo chiều dọc (tạo thành mảng 2x3).


<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 6: Sử Dụng np.stack()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo hai mảng NumPy, mỗi mảng chứa các số từ 1 đến 5. Thực hiện phép cộng hai mảng này.


<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 1: Sử Dụng np.add()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo một mảng NumPy chứa các số từ 5 đến 1. Tạo một mảng NumPy khác chứa các số từ 1 đến 5. Thực hiện phép trừ giữa mảng thứ nhất và mảng thứ hai.


<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 2: Sử Dụng np.subtract()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo một mảng NumPy 2x3 chứa các số từ 1 đến 6. Nhân tất cả các phần tử trong mảng với 2.


<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 3: Sử Dụng np.multiply()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo một mảng NumPy chứa các số [2, 4, 6, 8]. Tạo một mảng NumPy khác chứa [1, 2, 3, 4]. Thực hiện phép chia phần tử của mảng thứ nhất cho mảng thứ hai.


<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 4: Sử Dụng np.divide()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo một mảng NumPy chứa các số từ 1 đến 10. Tìm các vị trí của các phần tử có giá trị lớn hơn 5.


<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 5: Sử Dụng np.where()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo một mảng NumPy 2x3 chứa các số ngẫu nhiên. Tìm chỉ số của phần tử lớn nhất trong mảng.


<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 6: Sử Dụng np.argmax()
</pre>
  
</details>

In [ ]:
# Yêu cầu: Tạo một mảng NumPy chứa các số [3, 1, 4, 1, 5, 9, 2, 6]. Sắp xếp mảng này theo thứ tự tăng dần.


<details>
  <summary>Nhấn vào đây để xem gợi ý</summary>
  <pre>
Bài Tập 7: Sử Dụng np.sort()
</pre>
  
</details>