# Chapter 2 - Exercise 2: Đọc và chuyển dữ liệu, sau đó tính BMI theo điều kiện, truy xuất dữ liệu
### Dữ liệu được trích xuất từ http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights
> *Ghi chú:*
>Major League Baseball (MLB) là giải đấu bóng chày chuyên nghiệp. Major League Baseball có tổng cộng 30 đội bóng đến từ nhiều bang khác nhau của Mỹ và Canada (29 đội từ Mỹ và 1 đội từ Canada). MLB luôn được sự quan tâm lớn của hầu hết fan bóng chày trên toàn thế giới, và cũng được xem là giải đấu nổi tiếng và uy tín nhất, tập hợp những cầu thủ có trình độ cao nhất trong bộ môn này. 
Dữ liệu **heights.txt** (tính theo inches) và **weights.txt** (tính theo pounds) là chiều cao và cân nặng của các cầu thủ có tham gia 1 số giải của MLB. 

In [1]:
import numpy as np

# Phần 1: Đọc dữ liệu vào mảng

In [2]:
# 1. Đọc dữ liệu chiều cao từ file heights.txt vào mảng height


array([74, 74, 72, ..., 75, 75, 73])

In [3]:
# In ra số phần tử, kiểu dữ liệu của các phần tử mảng height.


1015


dtype('int32')

In [4]:
# 2. Đọc dữ liệu chiều cao từ file weights.txt vào mảng weight


array([180, 215, 210, ..., 205, 190, 195])

In [5]:
# In ra số phần tử, kiểu dữ liệu của các phần tử mảng weight.


1015


dtype('int32')

# Phần 2: Đổi Đơn Vị

In [6]:
# 3. Tạo mảng height_m (1 inch = 0.0254 meters) và weight_kg (1 pound = 0.453592 kilograms) từ height và weight.
# Làm tròn đến 2 chữ số thập phân


array([1.88, 1.88, 1.83, ..., 1.9 , 1.9 , 1.85])

array([81.65, 97.52, 95.25, ..., 92.99, 86.18, 88.45])

# Phần 3: Thống Kê Dữ Liệu

In [8]:
# 4. Tính chiều cao, cân nặng trung bình (mean) của các VĐV.


1.8704926108374385

91.33002955665026

In [10]:
# 5. Tính chiều cao, cân nặng trung vị (median) của các VĐV.


1.88

90.72

In [12]:
# 6. Tính độ lệch chuẩn (std) của chiều cao


0.05901785397875302

In [13]:
# 7. Tính độ lệch chuẩn (std) của cân nặng.


9.440554875313538

In [14]:
# 8. Cân nặng lớn nhất, nhỏ nhất


131.54

68.04

In [16]:
# 9. Chiều cao lớn nhất, nhỏ nhất


2.11

1.7

# Phần 4: Tạo Mảng 2 Chiều

In [18]:
# 10. Tạo một mảng numpy 2 chiều baseball bằng cách ghép mảng height_m và weight_kg theo cột.


array([[ 1.88, 81.65],
       [ 1.88, 97.52],
       [ 1.83, 95.25],
       ...,
       [ 1.9 , 92.99],
       [ 1.9 , 86.18],
       [ 1.85, 88.45]])

In [19]:
# 11. Tạo cột mới chứa chỉ số BMI của từng VĐV.


array([[ 1.88, 81.65, 23.1 ],
       [ 1.88, 97.52, 27.59],
       [ 1.83, 95.25, 28.44],
       ...,
       [ 1.9 , 92.99, 25.76],
       [ 1.9 , 86.18, 23.87],
       [ 1.85, 88.45, 25.84]])

# Phần 5: Truy Xuất Dữ Liệu

In [21]:
# 12. Truy xuất chiều cao của VĐV thứ 5


1.85

In [22]:
# 13. Truy xuất VĐV có chiều cao lớn nhất.


array([[  2.11, 117.93,  26.49]])

In [23]:
# 14. Truy xuất các VĐV có chiều cao lớn hơn 180 cm.


array([[ 1.88, 81.65, 23.1 ],
       [ 1.88, 97.52, 27.59],
       [ 1.83, 95.25, 28.44],
       ...,
       [ 1.9 , 92.99, 25.76],
       [ 1.9 , 86.18, 23.87],
       [ 1.85, 88.45, 25.84]])

In [24]:
# 15. Tìm VĐV có BMI lớn nhất.


array([[  1.83, 117.93,  35.21]])

In [25]:
# 16. Tìm cân nặng của VĐV có BMI nhỏ nhất.


array([70.76])

In [26]:
# 17. Tìm VĐV có cân nặng lớn hơn 90 kg và có chiều cao dưới 1.8m.


array([[ 1.75, 94.8 , 30.96],
       [ 1.75, 98.88, 32.29],
       [ 1.78, 92.99, 29.35],
       [ 1.78, 95.25, 30.06],
       [ 1.75, 90.72, 29.62],
       [ 1.73, 94.8 , 31.67],
       [ 1.78, 99.79, 31.5 ],
       [ 1.78, 92.99, 29.35]])

In [27]:
# 18. Tìm các VĐV có chiều cao lớn nhất hoặc cân nặng nhỏ nhất.


array([[  1.83,  68.04,  20.32],
       [  1.83,  68.04,  20.32],
       [  1.73,  68.04,  22.73],
       [  1.8 ,  68.04,  21.  ],
       [  2.11, 117.93,  26.49]])

# Phần 6: Thống Kê Trên Mảng 2 Chiều

In [28]:
# 19. Tính giá trị BMI trung bình của tất cả các VĐV.


26.091852216748766

In [29]:
# 20. Tính giá trị BMI trung bình của các VĐV có chiều cao lớn hơn 2m.


25.11375

In [30]:
# 21. Tính chiều cao trung bình của các VĐV có cân nặng dưới 70 kg.


1.7975

In [31]:
# 22. Tính số lượng VĐV có chiều cao lớn hơn 2 m và cân nặng dưới 100 kg.


10

In [32]:
# 23. Tính hệ số tương quan giữa chiều cao và cân nặng của các 


array([[1.        , 0.52984893],
       [0.52984893, 1.        ]])