## Import thư viện

In [3]:
import numpy as np

## Phần 1: Tạo mảng
### Tạo mảng 1 chiều

In [2]:
# 1. Tạo một mảng numpy 1 chiều even_numbers chứa 10 phần tử là các số chẵn trong phạm vi [2,20] 
even_number = np.random.randint(2,21, size=10)
even_number

NameError: name 'np' is not defined

In [8]:
# 2. Tạo một mảng numpy 1 chiều chứa 5 phần tử là các số chia cho 5 dư 1 (số nguyên có dạng 5x + 1) trong phạm vi [1,21].
mang = np.array([5 * i + 1 for i in range(5)])
mang

array([ 1,  6, 11, 16, 21])

In [5]:
# 3.Tạo 1 mảng 1 chiều gồm 11 phần tử cách đều nhau từ 0 đến 1
array_ = np.linspace(0,1,11) 
array_
# Cho biết khoảng cách giữa các giá trị retstep: 
retstep = array_[1] - array_[2]
retstep

np.float64(-0.1)

In [9]:
# 4.Tạo 1 mảng 1 chiều gồm 5 phần tử là các số nguyên ngẫu nhiên từ 1 đến 20
array_ = np.random.randint(1,20,5)
array_

array([ 4, 15, 16,  7, 17], dtype=int32)

In [4]:
# 5.Tạo mảng numpy 1 chiều chứa 10 phần tử với các phần tử ở index chẵn là 0 và ở index lẻ là số lẻ
array_  = np.array([0 if i % 2 == 0 else i for i in range(1,10) ])
array_ 

array([1, 0, 3, 0, 5, 0, 7, 0, 9])

In [8]:
# 6.Tạo 1 mảng 1 chiều gồm 10 phần tử có các phần tử ở index [0,3,6,9] là 3 và các phần tử còn lại là 1 
dk = [0,3,6,9]
array_ = np.array([1 for i in range(10)])
for i in dk:
    array_[i] = 3
array_

array([3, 1, 1, 3, 1, 1, 3, 1, 1, 3])

In [33]:
# 7. Tạo 1 mảng 1 chiều gồm 5 phần tử là các giá trị ngẫu nhiên (không trùng nhau) chia hết cho 3 và nhỏ hơn 30
# a = np.random.randint(0, 30, 5)
# a
array_ = np.random.choice(30,size = 5, replace= False)
array_
# Tạo mảng gồm các phần tử nhỏ hơn 30 và chia hết cho 3
array_2 = np.array([ i for i in range(30) if i % 3 == 0])
array_2
# Tạo mảng gồm 5 phần tử ngẫu nhiên (không trùng nhau) từ mảng vừa tạo
array_3 = [i for i in range(1,30) if i % 3 == 0]
array_3 = np.random.choice(array_3, size=5, replace= False)
array_3


array([24,  6, 18, 27,  3])

### Tạo mảng 2 chiều

In [40]:
# 8.Tạo mảng 2 chiều (3x4) arr_2d với các số chẵn ngẫu nhiên (không trùng nhau) < 50
arr_ = np.random.choice(50, size = (3, 4), replace=False).reshape(3,4)
arr_


array([[42, 22, 43,  1],
       [ 6, 37, 26, 49],
       [40, 25,  4, 48]], dtype=int32)

In [51]:
# 9. Tạo một mảng numpy 2 chiều (6x6) với các giá trị biên là 1 và các giá trị còn lại là 0
arr_ = np.zeros(6*6).reshape(6, 6)
arr_[0,:] = 1
arr_[-1,:] = 1
arr_[:,0] = 1
arr_[:, -1] = 1
arr_
# Tạo một mảng 2 chiều (6x6) với tất cả giá trị là 1
arr_ = 2*np.ones(6*6).reshape(6,6)
arr_


array([[2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.]])

In [61]:
# 10. Tạo một mảng numpy 2 chiều (3x3) với các giá trị trên đường chéo chính là 1 và các giá trị còn lại là 0 
n = 15
arr_ = np.zeros(n**2).reshape(n,n)
for i in range(arr_.shape[0]):
    arr_[i,i] = 7
arr_
# mảng kết quả


array([[7., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 7., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 7., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 7., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 7., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 7., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 7., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 7., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 7., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0., 0.

## Phần 2: Truy xuất
### Mảng 1 chiều
Từ mảng even_numbers đã tạo ở câu 1. Hãy thực hiện các truy xuất sau:

In [ ]:
# 11. Truy xuất giá trị phần tử thứ 3 của mảng even_numbers


In [ ]:
# 12. Truy xuất các phần tử từ vị trí thứ 2 đến vị trí thứ 4 (bao gồm cả vị trí thứ 4) của mảng even_numbers


In [ ]:
# 13.Truy xuất các phần tử lớn hơn 10 từ mảng even_numbers


In [ ]:
# 14. Truy xuất các phần tử chia hết cho 3 từ mảng even_numbers và lớn hơn 10


### Mảng 2 chiều
Từ mảng arr_2d đã tạo ở câu 8. Hãy thực hiện các truy xuất sau:

In [50]:
arr_2d = np.random.randint(100, size = (4,6))
arr_2d

array([[50, 55, 69, 57, 49, 84],
       [41, 52, 61, 46, 39, 20],
       [11,  3, 63, 56, 23, 58],
       [19, 43, 50, 41,  1,  6]], dtype=int32)

In [51]:
# 15.Cho biết phần tử ở hàng thứ 2 và cột thứ 3 của mảng arr_2d
arr_2d[2,3]

np.int32(56)

In [53]:
# 16. Hiển thị toàn bộ hàng 1 của mảng arr_2d
arr_2d[:1,]

array([[50, 55, 69, 57, 49, 84]], dtype=int32)

In [ ]:
# 17. Hiển thị toàn bộ cột 2 của mảng arr_2d
arr_2d[:,1]

array([[55],
       [52],
       [ 3],
       [43]], dtype=int32)

In [ ]:
# 18. Lọc các phần tử trong mảng arr_2d lớn hơn 30
arr_loc = arr_2d[arr_2d >30]

array([50, 55, 69, 57, 49, 84, 41, 52, 61, 46, 39, 63, 56, 58, 43, 50, 41],
      dtype=int32)

In [66]:
# 19. Lọc ra các dòng có phần tử ở cột thứ 2 trong mảng arr_2d chia hết cho 4
arr_2d = np.array([[50, 55, 69, 57, 49, 84],
       [41, 52, 9, 46, 39, 20],
       [11,  7, 4, 56, 23, 58],
       [19, 43, 50, 41,  1,  6]])
arr_loc = arr_2d[:,arr_2d[:,:] % 4 == 0]
arr_loc 

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [ ]:
# 20. Cho biết các giá trị trong mảng arr_2d nằm trong khoảng từ [10, 30]


## Phần 3: Thêm, xóa, sửa phần tử trong mảng
### Mảng 1 chiều
Từ mảng even_numbers đã tạo ở câu 1. Hãy thực hiện các yêu cầu sau:

In [66]:
# 21. Thêm giá trị 22 vào cuối mảng 
arr_  = np.ones(4)
arr_ = np.concatenate([arr_, [3]])
arr_

array([1., 1., 1., 1., 3.])

In [68]:
# 22. Thêm giá trị 30 vào vị trí thứ 5 của mảng
arr_ = np.insert(arr_,4, 30)
arr_

array([ 1.,  1.,  1.,  1., 30., 30.,  3.])

In [73]:
# 23. Tạo mảng temp là mảng even_numbers đã xóa giá trị tại vị trí thứ 7 
temp_ = np.array([range(10)])
arr_ = np.delete(temp_, 6)
arr_

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [79]:
# 24. Tạo mảng temp là mảng even_numbers đã xóa giá trị 8
arr_ = temp_[temp_ != 8]
arr_

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [3]:
# 25. Thay đổi các giá trị < 10 từ mảng even_numbers thành 10
import numpy as np
arr_ = np.random.randint(100, size = 20)
print(arr_)
arr_[arr_ < 10] = 10
arr_

[13 22  4 24 69 23 51 62  7 27 72 58 61 66 71  0 40 76 94 37]


array([13, 22, 10, 24, 69, 23, 51, 62, 10, 27, 72, 58, 61, 66, 71, 10, 40,
       76, 94, 37], dtype=int32)

### Mảng 2 chiều
Từ mảng arr_2d đã tạo ở câu 8. Hãy thực hiện các yêu cầu sau:

In [10]:
import numpy as np

arr_ = np.zeros(4*6).reshape(4,6)
arr_

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
# 26. Thêm hàng mới [10, 16, 20, 24] vào cuối mảng arr_2d

arr_2d = np.concatenate([np.zeros(10),[10, 16, 20, 24]])
arr_2d

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 16., 20.,
       24.])

In [24]:
arr_ = np.random.randint(100, size = (4,5))
arr_

array([[28, 32, 99,  8, 96],
       [54, 54, 39, 29,  3],
       [55, 87,  8, 49, 82],
       [72, 15, 89, 95, 30]], dtype=int32)

In [ ]:
arr_[0:3,0:4]   

array([[28, 32, 99,  8],
       [54, 54, 39, 29],
       [55, 87,  8, 49]], dtype=int32)

In [39]:
# 27. Thêm cột mới [50, 60, 70, 80] vào cuối mảng arr_2d


In [40]:
# 28. Tạo mảng temp là mảng arr_2d đã xóa hàng thứ 2


In [41]:
# 29. Tạo mảng temp là mảng arr_2d đã xóa cột thứ 3


In [42]:
# 30. Sửa giá trị tại dòng 1, cột 2 thành 30


In [43]:
# 31. Sửa các giá trị lớn hơn 10 và nhỏ hơn 20 trong arr_2d thành 20


In [44]:
# 32. Sửa các giá trị nhỏ hơn 30 và không chia hết cho 4 tại dòng đầu tiên trong arr_2d thành 30
