>tính độ lệch chuẩn 

In [38]:
import math

try:
    with open("data.txt", "r") as file:
        noiDung = file.read()
except FileNotFoundError:
    print("File không tồn tại")
    exit()


In [39]:
listCCao = noiDung.split(", ")
listCCao = [float(i) for i in listCCao]

print(listCCao)

[1.57, 1.65, 1.63, 1.58, 1.57, 1.68, 1.65, 1.7, 1.64, 1.67]


In [40]:
caoMax = 0
caoMin = listCCao[0] 

for i in listCCao:
    if i > caoMax:
        caoMax = i
        continue
    elif i < caoMin:
        caoMin = i
        continue
print(caoMax, caoMin)
    

1.7 1.57


In [41]:
tongChieuCao = 0

for i in listCCao:
    tongChieuCao += i

chieuCaoTrungBinh = tongChieuCao/len(listCCao)

print(f"tong chieu cao: {tongChieuCao}")
print(f"chieu cao trung binh: {chieuCaoTrungBinh}")

tong chieu cao: 16.34
chieu cao trung binh: 1.634


In [42]:
tongXUBinh = 0

for i in listCCao:
    tongXUBinh += (i - chieuCaoTrungBinh) ** 2

doLechChuan = math.sqrt(tongXUBinh / len(listCCao))

print(f"do lech chuan: {doLechChuan}")

do lech chuan: 0.04409081537009715


In [6]:
import numpy as np

arr_ = np.zeros(10)
arr_ = np.insert(arr_, 1, 10)
arr_

array([ 0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [ ]:
arr_ = np.delete(arr_, 1)
arr_

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr_ = np.zeros(3)
arr_ 

In [5]:
arr_ = np.genfromtxt('weights.txt', delimiter=',')
arr_ 

array([180., 215., 210., ..., 205., 190., 195.])